### ISSUE TITLE
The app crashes on Nexus 5x  api 24 

### ISSUE THREAD

**Issue by sachincool** [coding-blocks/GSoC-Info-Android#4]
issue :-  Line number 53 on TimeLineAdapter  returns a  nullpointer exception .
![screenshot_1505137552](https://user-images.githubusercontent.com/25671488/30277548-c678b812-9725-11e7-886d-18beb66f35f5.png)

**Comment by the-dagger** [comment]
Thanks!
The data source has been shifted to database whereas I was previously populating the data from static variables.
Have to change all the fetch methods to fetch data from db instead of those static variables now.
Will be sending a commit which fixes this soon.

**Comment by the-dagger** [comment]
Fixed.
